// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

/// @title IVerifier - Ed25519 signature verification via Groth16 proof
/// @notice Wrapper that decompresses Ed25519 points, constructs gnark public inputs,
///         and forwards to the underlying Groth16 verifier.
interface IVerifier {
    /// @notice Verify an Ed25519 signature using a Groth16 ZK proof
    /// @param proof The Groth16 proof (8 uint256s: Ar, Bs, Krs)
    /// @param commitments The proof commitments (2 uint256s)
    /// @param commitmentPok The proof of knowledge for commitments (2 uint256s)
    /// @param signature The Ed25519 signature: [R (32 bytes compressed), S (32 bytes scalar)]
    /// @param pubkey The Ed25519 public key (32 bytes compressed)
    /// @param message The raw signed message bytes (used in SHA512(R || pubkey || message))
    function verifyProof(
        uint256[8] calldata proof,
        uint256[2] calldata commitments,
        uint256[2] calldata commitmentPok,
        bytes32[2] calldata signature,
        bytes32 pubkey,
        bytes calldata message
    ) external returns (bool);
}

/// @title IGroth16Verifier - Raw Groth16 proof verifier (auto-generated from circuit)
/// @notice This contract is generated by gnark from the circuit's verification key.
///         The number of public inputs (24) = 6 field elements (R.X, R.Y, S, Hash, A.X, A.Y)
///         x 4 limbs each. Each limb is 64-bit LE.
interface IGroth16Verifier {
    function verifyProof(
        uint256[8] calldata proof,
        uint256[2] calldata commitments,
        uint256[2] calldata commitmentPok,
        uint256[24] calldata input
    ) external view;
}