// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: attestor/attestor.proto

package attestorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttestorService_Info_FullMethodName                  = "/attestor.AttestorService/Info"
	AttestorService_AttestedUpTo_FullMethodName          = "/attestor.AttestorService/AttestedUpTo"
	AttestorService_AttestedRootAtOrBelow_FullMethodName = "/attestor.AttestorService/AttestedRootAtOrBelow"
	AttestorService_WatchAttested_FullMethodName         = "/attestor.AttestorService/WatchAttested"
)

// AttestorServiceClient is the client API for AttestorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The attestor sidecar service definition.
// The attestor runs next to a verify-mode replica of an OP Stack chain and
// maintains a feed of output roots it has verified by replaying the L2 state
// transition from L1 data. The relayer connects to this service and relays
// only against roots the attestor has affirmed.
type AttestorServiceClient interface {
	// Report every attested chain with its replica heads and feed frontiers.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// Return the attested frontier: the highest attested root for a chain.
	AttestedUpTo(ctx context.Context, in *AttestedUpToRequest, opts ...grpc.CallOption) (*AttestedUpToResponse, error)
	// Return the highest attested root at or below an L2 block — the query
	// the relayer uses to pick a root that covers a packet's height.
	AttestedRootAtOrBelow(ctx context.Context, in *AttestedRootAtOrBelowRequest, opts ...grpc.CallOption) (*AttestedRootAtOrBelowResponse, error)
	// Stream attested-frontier advances for a chain. The server sends the
	// current frontier on subscribe, then a message whenever it grows.
	WatchAttested(ctx context.Context, in *WatchAttestedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchAttestedResponse], error)
}

type attestorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestorServiceClient(cc grpc.ClientConnInterface) AttestorServiceClient {
	return &attestorServiceClient{cc}
}

func (c *attestorServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, AttestorService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestorServiceClient) AttestedUpTo(ctx context.Context, in *AttestedUpToRequest, opts ...grpc.CallOption) (*AttestedUpToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestedUpToResponse)
	err := c.cc.Invoke(ctx, AttestorService_AttestedUpTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestorServiceClient) AttestedRootAtOrBelow(ctx context.Context, in *AttestedRootAtOrBelowRequest, opts ...grpc.CallOption) (*AttestedRootAtOrBelowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestedRootAtOrBelowResponse)
	err := c.cc.Invoke(ctx, AttestorService_AttestedRootAtOrBelow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestorServiceClient) WatchAttested(ctx context.Context, in *WatchAttestedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchAttestedResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttestorService_ServiceDesc.Streams[0], AttestorService_WatchAttested_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchAttestedRequest, WatchAttestedResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttestorService_WatchAttestedClient = grpc.ServerStreamingClient[WatchAttestedResponse]

// AttestorServiceServer is the server API for AttestorService service.
// All implementations must embed UnimplementedAttestorServiceServer
// for forward compatibility.
//
// The attestor sidecar service definition.
// The attestor runs next to a verify-mode replica of an OP Stack chain and
// maintains a feed of output roots it has verified by replaying the L2 state
// transition from L1 data. The relayer connects to this service and relays
// only against roots the attestor has affirmed.
type AttestorServiceServer interface {
	// Report every attested chain with its replica heads and feed frontiers.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// Return the attested frontier: the highest attested root for a chain.
	AttestedUpTo(context.Context, *AttestedUpToRequest) (*AttestedUpToResponse, error)
	// Return the highest attested root at or below an L2 block — the query
	// the relayer uses to pick a root that covers a packet's height.
	AttestedRootAtOrBelow(context.Context, *AttestedRootAtOrBelowRequest) (*AttestedRootAtOrBelowResponse, error)
	// Stream attested-frontier advances for a chain. The server sends the
	// current frontier on subscribe, then a message whenever it grows.
	WatchAttested(*WatchAttestedRequest, grpc.ServerStreamingServer[WatchAttestedResponse]) error
	mustEmbedUnimplementedAttestorServiceServer()
}

// UnimplementedAttestorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestorServiceServer struct{}

func (UnimplementedAttestorServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAttestorServiceServer) AttestedUpTo(context.Context, *AttestedUpToRequest) (*AttestedUpToResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttestedUpTo not implemented")
}
func (UnimplementedAttestorServiceServer) AttestedRootAtOrBelow(context.Context, *AttestedRootAtOrBelowRequest) (*AttestedRootAtOrBelowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttestedRootAtOrBelow not implemented")
}
func (UnimplementedAttestorServiceServer) WatchAttested(*WatchAttestedRequest, grpc.ServerStreamingServer[WatchAttestedResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchAttested not implemented")
}
func (UnimplementedAttestorServiceServer) mustEmbedUnimplementedAttestorServiceServer() {}
func (UnimplementedAttestorServiceServer) testEmbeddedByValue()                         {}

// UnsafeAttestorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestorServiceServer will
// result in compilation errors.
type UnsafeAttestorServiceServer interface {
	mustEmbedUnimplementedAttestorServiceServer()
}

func RegisterAttestorServiceServer(s grpc.ServiceRegistrar, srv AttestorServiceServer) {
	// If the following call panics, it indicates UnimplementedAttestorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttestorService_ServiceDesc, srv)
}

func _AttestorService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestorService_AttestedUpTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestedUpToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).AttestedUpTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_AttestedUpTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).AttestedUpTo(ctx, req.(*AttestedUpToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestorService_AttestedRootAtOrBelow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestedRootAtOrBelowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).AttestedRootAtOrBelow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_AttestedRootAtOrBelow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).AttestedRootAtOrBelow(ctx, req.(*AttestedRootAtOrBelowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestorService_WatchAttested_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAttestedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AttestorServiceServer).WatchAttested(m, &grpc.GenericServerStream[WatchAttestedRequest, WatchAttestedResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttestorService_WatchAttestedServer = grpc.ServerStreamingServer[WatchAttestedResponse]

// AttestorService_ServiceDesc is the grpc.ServiceDesc for AttestorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attestor.AttestorService",
	HandlerType: (*AttestorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _AttestorService_Info_Handler,
		},
		{
			MethodName: "AttestedUpTo",
			Handler:    _AttestorService_AttestedUpTo_Handler,
		},
		{
			MethodName: "AttestedRootAtOrBelow",
			Handler:    _AttestorService_AttestedRootAtOrBelow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchAttested",
			Handler:       _AttestorService_WatchAttested_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "attestor/attestor.proto",
}
