// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: attestor/attestor.proto

package attestorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunMode selects which replica head must include a requested block.
type RunMode int32

const (
	RunMode_RUN_MODE_UNSPECIFIED RunMode = 0
	RunMode_RUN_MODE_UNSAFE      RunMode = 1
	RunMode_RUN_MODE_SAFE        RunMode = 2
	RunMode_RUN_MODE_FINALIZED   RunMode = 3
)

// Enum value maps for RunMode.
var (
	RunMode_name = map[int32]string{
		0: "RUN_MODE_UNSPECIFIED",
		1: "RUN_MODE_UNSAFE",
		2: "RUN_MODE_SAFE",
		3: "RUN_MODE_FINALIZED",
	}
	RunMode_value = map[string]int32{
		"RUN_MODE_UNSPECIFIED": 0,
		"RUN_MODE_UNSAFE":      1,
		"RUN_MODE_SAFE":        2,
		"RUN_MODE_FINALIZED":   3,
	}
)

func (x RunMode) Enum() *RunMode {
	p := new(RunMode)
	*p = x
	return p
}

func (x RunMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunMode) Descriptor() protoreflect.EnumDescriptor {
	return file_attestor_attestor_proto_enumTypes[0].Descriptor()
}

func (RunMode) Type() protoreflect.EnumType {
	return &file_attestor_attestor_proto_enumTypes[0]
}

func (x RunMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunMode.Descriptor instead.
func (RunMode) EnumDescriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{0}
}

// AttestedRoot is one independently verified rollup commitment.
type AttestedRoot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// L2BlockNumber is the execution block committed by this attestation.
	L2BlockNumber uint64 `protobuf:"varint,1,opt,name=l2_block_number,json=l2BlockNumber,proto3" json:"l2_block_number,omitempty"`
	// Root is chain-specific: an OP output root or an Arbitrum L2 state root.
	Root []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	// Source identifies the commitment mechanism, such as "game", "derived",
	// or "assertion".
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Provenance carries the chain-specific on-chain object that the relayer
	// must prove. At most one identifier can be present.
	//
	// Types that are valid to be assigned to Provenance:
	//
	//	*AttestedRoot_GameIndex
	//	*AttestedRoot_AssertionHash
	//	*AttestedRoot_LegacyNode
	Provenance isAttestedRoot_Provenance `protobuf_oneof:"provenance"`
	// Provisional is true while the commitment still awaits the chain-specific
	// irreversible-finality check.
	Provisional bool `protobuf:"varint,5,opt,name=provisional,proto3" json:"provisional,omitempty"`
	// AttestedAt is the Unix timestamp when the local verifier accepted it.
	AttestedAt    int64 `protobuf:"varint,6,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedRoot) Reset() {
	*x = AttestedRoot{}
	mi := &file_attestor_attestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRoot) ProtoMessage() {}

func (x *AttestedRoot) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRoot.ProtoReflect.Descriptor instead.
func (*AttestedRoot) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{0}
}

func (x *AttestedRoot) GetL2BlockNumber() uint64 {
	if x != nil {
		return x.L2BlockNumber
	}
	return 0
}

func (x *AttestedRoot) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *AttestedRoot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AttestedRoot) GetProvenance() isAttestedRoot_Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *AttestedRoot) GetGameIndex() uint64 {
	if x != nil {
		if x, ok := x.Provenance.(*AttestedRoot_GameIndex); ok {
			return x.GameIndex
		}
	}
	return 0
}

func (x *AttestedRoot) GetAssertionHash() []byte {
	if x != nil {
		if x, ok := x.Provenance.(*AttestedRoot_AssertionHash); ok {
			return x.AssertionHash
		}
	}
	return nil
}

func (x *AttestedRoot) GetLegacyNode() *LegacyNode {
	if x != nil {
		if x, ok := x.Provenance.(*AttestedRoot_LegacyNode); ok {
			return x.LegacyNode
		}
	}
	return nil
}

func (x *AttestedRoot) GetProvisional() bool {
	if x != nil {
		return x.Provisional
	}
	return false
}

func (x *AttestedRoot) GetAttestedAt() int64 {
	if x != nil {
		return x.AttestedAt
	}
	return 0
}

type isAttestedRoot_Provenance interface {
	isAttestedRoot_Provenance()
}

type AttestedRoot_GameIndex struct {
	// GameIndex identifies an OP dispute game when source is "game".
	GameIndex uint64 `protobuf:"varint,4,opt,name=game_index,json=gameIndex,proto3,oneof"`
}

type AttestedRoot_AssertionHash struct {
	// AssertionHash identifies an Arbitrum BoLD assertion when source is
	// "assertion".
	AssertionHash []byte `protobuf:"bytes,7,opt,name=assertion_hash,json=assertionHash,proto3,oneof"`
}

type AttestedRoot_LegacyNode struct {
	// LegacyNode identifies a pre-BoLD Arbitrum Nitro node.
	LegacyNode *LegacyNode `protobuf:"bytes,8,opt,name=legacy_node,json=legacyNode,proto3,oneof"`
}

func (*AttestedRoot_GameIndex) isAttestedRoot_Provenance() {}

func (*AttestedRoot_AssertionHash) isAttestedRoot_Provenance() {}

func (*AttestedRoot_LegacyNode) isAttestedRoot_Provenance() {}

// LegacyNode identifies one pre-BoLD Nitro RollupCore node.
type LegacyNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// NodeNumber is the uint64 key in RollupCore's _nodes mapping.
	NodeNumber uint64 `protobuf:"varint,1,opt,name=node_number,json=nodeNumber,proto3" json:"node_number,omitempty"`
	// NodeHash is the hash indexed by the corresponding NodeCreated event.
	NodeHash      []byte `protobuf:"bytes,2,opt,name=node_hash,json=nodeHash,proto3" json:"node_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegacyNode) Reset() {
	*x = LegacyNode{}
	mi := &file_attestor_attestor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyNode) ProtoMessage() {}

func (x *LegacyNode) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegacyNode.ProtoReflect.Descriptor instead.
func (*LegacyNode) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{1}
}

func (x *LegacyNode) GetNodeNumber() uint64 {
	if x != nil {
		return x.NodeNumber
	}
	return 0
}

func (x *LegacyNode) GetNodeHash() []byte {
	if x != nil {
		return x.NodeHash
	}
	return nil
}

// InfoRequest selects all configured chains.
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{2}
}

// ChainInfo reports one configured attestor.
type ChainInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SrcChain is the configured source-chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// AttestationHead is the configured gating head.
	AttestationHead string `protobuf:"bytes,2,opt,name=attestation_head,json=attestationHead,proto3" json:"attestation_head,omitempty"`
	// ReplicaSeen is true after the replica has reported sync status.
	ReplicaSeen bool `protobuf:"varint,3,opt,name=replica_seen,json=replicaSeen,proto3" json:"replica_seen,omitempty"`
	// ReplicaUnsafeL2 is the replica's unsafe L2 head.
	ReplicaUnsafeL2 uint64 `protobuf:"varint,4,opt,name=replica_unsafe_l2,json=replicaUnsafeL2,proto3" json:"replica_unsafe_l2,omitempty"`
	// ReplicaSafeL2 is the replica's safe L2 head.
	ReplicaSafeL2 uint64 `protobuf:"varint,5,opt,name=replica_safe_l2,json=replicaSafeL2,proto3" json:"replica_safe_l2,omitempty"`
	// ReplicaFinalizedL2 is the replica's finalized L2 head.
	ReplicaFinalizedL2 uint64 `protobuf:"varint,6,opt,name=replica_finalized_l2,json=replicaFinalizedL2,proto3" json:"replica_finalized_l2,omitempty"`
	// PendingGames is the number of ingested OP games awaiting a verdict.
	PendingGames uint64 `protobuf:"varint,7,opt,name=pending_games,json=pendingGames,proto3" json:"pending_games,omitempty"`
	// AttestedUpTo is the non-provisional frontier, when one exists.
	AttestedUpTo *AttestedRoot `protobuf:"bytes,8,opt,name=attested_up_to,json=attestedUpTo,proto3" json:"attested_up_to,omitempty"`
	// AttestedUpToProvisional is the frontier including provisional entries.
	AttestedUpToProvisional *AttestedRoot `protobuf:"bytes,9,opt,name=attested_up_to_provisional,json=attestedUpToProvisional,proto3" json:"attested_up_to_provisional,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChainInfo) Reset() {
	*x = ChainInfo{}
	mi := &file_attestor_attestor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainInfo) ProtoMessage() {}

func (x *ChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainInfo.ProtoReflect.Descriptor instead.
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{3}
}

func (x *ChainInfo) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *ChainInfo) GetAttestationHead() string {
	if x != nil {
		return x.AttestationHead
	}
	return ""
}

func (x *ChainInfo) GetReplicaSeen() bool {
	if x != nil {
		return x.ReplicaSeen
	}
	return false
}

func (x *ChainInfo) GetReplicaUnsafeL2() uint64 {
	if x != nil {
		return x.ReplicaUnsafeL2
	}
	return 0
}

func (x *ChainInfo) GetReplicaSafeL2() uint64 {
	if x != nil {
		return x.ReplicaSafeL2
	}
	return 0
}

func (x *ChainInfo) GetReplicaFinalizedL2() uint64 {
	if x != nil {
		return x.ReplicaFinalizedL2
	}
	return 0
}

func (x *ChainInfo) GetPendingGames() uint64 {
	if x != nil {
		return x.PendingGames
	}
	return 0
}

func (x *ChainInfo) GetAttestedUpTo() *AttestedRoot {
	if x != nil {
		return x.AttestedUpTo
	}
	return nil
}

func (x *ChainInfo) GetAttestedUpToProvisional() *AttestedRoot {
	if x != nil {
		return x.AttestedUpToProvisional
	}
	return nil
}

// InfoResponse reports every configured chain.
type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chains        []*ChainInfo           `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{4}
}

func (x *InfoResponse) GetChains() []*ChainInfo {
	if x != nil {
		return x.Chains
	}
	return nil
}

// AttestedUpToRequest selects one source-chain frontier.
type AttestedUpToRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SrcChain is the configured source-chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// IncludeProvisional allows locally verified commitments that still await
	// irreversible finality.
	IncludeProvisional bool `protobuf:"varint,2,opt,name=include_provisional,json=includeProvisional,proto3" json:"include_provisional,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttestedUpToRequest) Reset() {
	*x = AttestedUpToRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedUpToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedUpToRequest) ProtoMessage() {}

func (x *AttestedUpToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedUpToRequest.ProtoReflect.Descriptor instead.
func (*AttestedUpToRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{5}
}

func (x *AttestedUpToRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *AttestedUpToRequest) GetIncludeProvisional() bool {
	if x != nil {
		return x.IncludeProvisional
	}
	return false
}

// AttestedUpToResponse contains the source-chain frontier when one exists.
type AttestedUpToResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found is false before any qualifying commitment has been attested.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Root is set only when Found is true.
	Root          *AttestedRoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedUpToResponse) Reset() {
	*x = AttestedUpToResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedUpToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedUpToResponse) ProtoMessage() {}

func (x *AttestedUpToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedUpToResponse.ProtoReflect.Descriptor instead.
func (*AttestedUpToResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{6}
}

func (x *AttestedUpToResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *AttestedUpToResponse) GetRoot() *AttestedRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

// AttestedRootAtOrBelowRequest selects an inclusive L2-height bound.
type AttestedRootAtOrBelowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SrcChain is the configured source-chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// L2BlockNumber is the inclusive upper bound.
	L2BlockNumber uint64 `protobuf:"varint,2,opt,name=l2_block_number,json=l2BlockNumber,proto3" json:"l2_block_number,omitempty"`
	// IncludeProvisional allows locally verified commitments that still await
	// irreversible finality.
	IncludeProvisional bool `protobuf:"varint,3,opt,name=include_provisional,json=includeProvisional,proto3" json:"include_provisional,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttestedRootAtOrBelowRequest) Reset() {
	*x = AttestedRootAtOrBelowRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRootAtOrBelowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRootAtOrBelowRequest) ProtoMessage() {}

func (x *AttestedRootAtOrBelowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRootAtOrBelowRequest.ProtoReflect.Descriptor instead.
func (*AttestedRootAtOrBelowRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{7}
}

func (x *AttestedRootAtOrBelowRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *AttestedRootAtOrBelowRequest) GetL2BlockNumber() uint64 {
	if x != nil {
		return x.L2BlockNumber
	}
	return 0
}

func (x *AttestedRootAtOrBelowRequest) GetIncludeProvisional() bool {
	if x != nil {
		return x.IncludeProvisional
	}
	return false
}

// AttestedRootAtOrBelowResponse contains the best qualifying commitment.
type AttestedRootAtOrBelowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Found is false when no qualifying commitment exists at or below the bound.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// Root is set only when Found is true.
	Root          *AttestedRoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedRootAtOrBelowResponse) Reset() {
	*x = AttestedRootAtOrBelowResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRootAtOrBelowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRootAtOrBelowResponse) ProtoMessage() {}

func (x *AttestedRootAtOrBelowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRootAtOrBelowResponse.ProtoReflect.Descriptor instead.
func (*AttestedRootAtOrBelowResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{8}
}

func (x *AttestedRootAtOrBelowResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *AttestedRootAtOrBelowResponse) GetRoot() *AttestedRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

// WatchAttestedRequest selects a source-chain frontier stream.
type WatchAttestedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SrcChain is the configured source-chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// IncludeProvisional allows provisional entries to advance the stream.
	IncludeProvisional bool `protobuf:"varint,2,opt,name=include_provisional,json=includeProvisional,proto3" json:"include_provisional,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchAttestedRequest) Reset() {
	*x = WatchAttestedRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAttestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAttestedRequest) ProtoMessage() {}

func (x *WatchAttestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAttestedRequest.ProtoReflect.Descriptor instead.
func (*WatchAttestedRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{9}
}

func (x *WatchAttestedRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *WatchAttestedRequest) GetIncludeProvisional() bool {
	if x != nil {
		return x.IncludeProvisional
	}
	return false
}

// WatchAttestedResponse contains one frontier update.
type WatchAttestedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Root is the current frontier entry. Consumers must treat each message as
	// the authoritative frontier — a provisional watch can see the same height
	// again with a corrected root or cleared provisional flag, or a lower
	// height after a provisional revocation.
	Root          *AttestedRoot `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAttestedResponse) Reset() {
	*x = WatchAttestedResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAttestedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAttestedResponse) ProtoMessage() {}

func (x *WatchAttestedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAttestedResponse.ProtoReflect.Descriptor instead.
func (*WatchAttestedResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{10}
}

func (x *WatchAttestedResponse) GetRoot() *AttestedRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

// VerifyStateRootRequest identifies one L2 block and its expected commitment.
type VerifyStateRootRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BlockNumber is the L2 block height.
	BlockNumber uint64 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// ExpectedStateRoot must contain exactly 32 bytes.
	ExpectedStateRoot []byte `protobuf:"bytes,2,opt,name=expected_state_root,json=expectedStateRoot,proto3" json:"expected_state_root,omitempty"`
	// ExpectedBlockHash is optional. When set, it must contain exactly 32 bytes
	// and must also match the replica's canonical block.
	ExpectedBlockHash []byte `protobuf:"bytes,3,opt,name=expected_block_hash,json=expectedBlockHash,proto3" json:"expected_block_hash,omitempty"`
	// RunMode selects the replica finality level for this verification request.
	RunMode       RunMode `protobuf:"varint,4,opt,name=run_mode,json=runMode,proto3,enum=attestor.RunMode" json:"run_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStateRootRequest) Reset() {
	*x = VerifyStateRootRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStateRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStateRootRequest) ProtoMessage() {}

func (x *VerifyStateRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStateRootRequest.ProtoReflect.Descriptor instead.
func (*VerifyStateRootRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyStateRootRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *VerifyStateRootRequest) GetExpectedStateRoot() []byte {
	if x != nil {
		return x.ExpectedStateRoot
	}
	return nil
}

func (x *VerifyStateRootRequest) GetExpectedBlockHash() []byte {
	if x != nil {
		return x.ExpectedBlockHash
	}
	return nil
}

func (x *VerifyStateRootRequest) GetRunMode() RunMode {
	if x != nil {
		return x.RunMode
	}
	return RunMode_RUN_MODE_UNSPECIFIED
}

// VerifyStateRootResponse returns the replica's canonical block commitment.
type VerifyStateRootResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Valid is true only when all supplied expectations match the replica.
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// BlockNumber echoes the verified L2 height.
	BlockNumber uint64 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	// BlockHash is the replica's canonical block hash.
	BlockHash []byte `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// StateRoot is the root committed by the canonical block header.
	StateRoot     []byte `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStateRootResponse) Reset() {
	*x = VerifyStateRootResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStateRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStateRootResponse) ProtoMessage() {}

func (x *VerifyStateRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStateRootResponse.ProtoReflect.Descriptor instead.
func (*VerifyStateRootResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyStateRootResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyStateRootResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *VerifyStateRootResponse) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *VerifyStateRootResponse) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

var File_attestor_attestor_proto protoreflect.FileDescriptor

const file_attestor_attestor_proto_rawDesc = "" +
	"\n" +
	"\x17attestor/attestor.proto\x12\battestor\"\xb6\x02\n" +
	"\fAttestedRoot\x12&\n" +
	"\x0fl2_block_number\x18\x01 \x01(\x04R\rl2BlockNumber\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\n" +
	"game_index\x18\x04 \x01(\x04H\x00R\tgameIndex\x12'\n" +
	"\x0eassertion_hash\x18\a \x01(\fH\x00R\rassertionHash\x127\n" +
	"\vlegacy_node\x18\b \x01(\v2\x14.attestor.LegacyNodeH\x00R\n" +
	"legacyNode\x12 \n" +
	"\vprovisional\x18\x05 \x01(\bR\vprovisional\x12\x1f\n" +
	"\vattested_at\x18\x06 \x01(\x03R\n" +
	"attestedAtB\f\n" +
	"\n" +
	"provenance\"J\n" +
	"\n" +
	"LegacyNode\x12\x1f\n" +
	"\vnode_number\x18\x01 \x01(\x04R\n" +
	"nodeNumber\x12\x1b\n" +
	"\tnode_hash\x18\x02 \x01(\fR\bnodeHash\"\r\n" +
	"\vInfoRequest\"\xb4\x03\n" +
	"\tChainInfo\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12)\n" +
	"\x10attestation_head\x18\x02 \x01(\tR\x0fattestationHead\x12!\n" +
	"\freplica_seen\x18\x03 \x01(\bR\vreplicaSeen\x12*\n" +
	"\x11replica_unsafe_l2\x18\x04 \x01(\x04R\x0freplicaUnsafeL2\x12&\n" +
	"\x0freplica_safe_l2\x18\x05 \x01(\x04R\rreplicaSafeL2\x120\n" +
	"\x14replica_finalized_l2\x18\x06 \x01(\x04R\x12replicaFinalizedL2\x12#\n" +
	"\rpending_games\x18\a \x01(\x04R\fpendingGames\x12<\n" +
	"\x0eattested_up_to\x18\b \x01(\v2\x16.attestor.AttestedRootR\fattestedUpTo\x12S\n" +
	"\x1aattested_up_to_provisional\x18\t \x01(\v2\x16.attestor.AttestedRootR\x17attestedUpToProvisional\";\n" +
	"\fInfoResponse\x12+\n" +
	"\x06chains\x18\x01 \x03(\v2\x13.attestor.ChainInfoR\x06chains\"c\n" +
	"\x13AttestedUpToRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12/\n" +
	"\x13include_provisional\x18\x02 \x01(\bR\x12includeProvisional\"X\n" +
	"\x14AttestedUpToResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\x04root\x18\x02 \x01(\v2\x16.attestor.AttestedRootR\x04root\"\x94\x01\n" +
	"\x1cAttestedRootAtOrBelowRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12&\n" +
	"\x0fl2_block_number\x18\x02 \x01(\x04R\rl2BlockNumber\x12/\n" +
	"\x13include_provisional\x18\x03 \x01(\bR\x12includeProvisional\"a\n" +
	"\x1dAttestedRootAtOrBelowResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\x04root\x18\x02 \x01(\v2\x16.attestor.AttestedRootR\x04root\"d\n" +
	"\x14WatchAttestedRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12/\n" +
	"\x13include_provisional\x18\x02 \x01(\bR\x12includeProvisional\"C\n" +
	"\x15WatchAttestedResponse\x12*\n" +
	"\x04root\x18\x01 \x01(\v2\x16.attestor.AttestedRootR\x04root\"\xc9\x01\n" +
	"\x16VerifyStateRootRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12.\n" +
	"\x13expected_state_root\x18\x02 \x01(\fR\x11expectedStateRoot\x12.\n" +
	"\x13expected_block_hash\x18\x03 \x01(\fR\x11expectedBlockHash\x12,\n" +
	"\brun_mode\x18\x04 \x01(\x0e2\x11.attestor.RunModeR\arunMode\"\x90\x01\n" +
	"\x17VerifyStateRootResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fR\tstateRoot*c\n" +
	"\aRunMode\x12\x18\n" +
	"\x14RUN_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRUN_MODE_UNSAFE\x10\x01\x12\x11\n" +
	"\rRUN_MODE_SAFE\x10\x02\x12\x16\n" +
	"\x12RUN_MODE_FINALIZED\x10\x032\xad\x03\n" +
	"\x0fAttestorService\x125\n" +
	"\x04Info\x12\x15.attestor.InfoRequest\x1a\x16.attestor.InfoResponse\x12M\n" +
	"\fAttestedUpTo\x12\x1d.attestor.AttestedUpToRequest\x1a\x1e.attestor.AttestedUpToResponse\x12h\n" +
	"\x15AttestedRootAtOrBelow\x12&.attestor.AttestedRootAtOrBelowRequest\x1a'.attestor.AttestedRootAtOrBelowResponse\x12R\n" +
	"\rWatchAttested\x12\x1e.attestor.WatchAttestedRequest\x1a\x1f.attestor.WatchAttestedResponse0\x01\x12V\n" +
	"\x0fVerifyStateRoot\x12 .attestor.VerifyStateRootRequest\x1a!.attestor.VerifyStateRootResponseB$Z\"attestor/types/attestor;attestorpbb\x06proto3"

var (
	file_attestor_attestor_proto_rawDescOnce sync.Once
	file_attestor_attestor_proto_rawDescData []byte
)

func file_attestor_attestor_proto_rawDescGZIP() []byte {
	file_attestor_attestor_proto_rawDescOnce.Do(func() {
		file_attestor_attestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestor_attestor_proto_rawDesc), len(file_attestor_attestor_proto_rawDesc)))
	})
	return file_attestor_attestor_proto_rawDescData
}

var file_attestor_attestor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_attestor_attestor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_attestor_attestor_proto_goTypes = []any{
	(RunMode)(0),                          // 0: attestor.RunMode
	(*AttestedRoot)(nil),                  // 1: attestor.AttestedRoot
	(*LegacyNode)(nil),                    // 2: attestor.LegacyNode
	(*InfoRequest)(nil),                   // 3: attestor.InfoRequest
	(*ChainInfo)(nil),                     // 4: attestor.ChainInfo
	(*InfoResponse)(nil),                  // 5: attestor.InfoResponse
	(*AttestedUpToRequest)(nil),           // 6: attestor.AttestedUpToRequest
	(*AttestedUpToResponse)(nil),          // 7: attestor.AttestedUpToResponse
	(*AttestedRootAtOrBelowRequest)(nil),  // 8: attestor.AttestedRootAtOrBelowRequest
	(*AttestedRootAtOrBelowResponse)(nil), // 9: attestor.AttestedRootAtOrBelowResponse
	(*WatchAttestedRequest)(nil),          // 10: attestor.WatchAttestedRequest
	(*WatchAttestedResponse)(nil),         // 11: attestor.WatchAttestedResponse
	(*VerifyStateRootRequest)(nil),        // 12: attestor.VerifyStateRootRequest
	(*VerifyStateRootResponse)(nil),       // 13: attestor.VerifyStateRootResponse
}
var file_attestor_attestor_proto_depIdxs = []int32{
	2,  // 0: attestor.AttestedRoot.legacy_node:type_name -> attestor.LegacyNode
	1,  // 1: attestor.ChainInfo.attested_up_to:type_name -> attestor.AttestedRoot
	1,  // 2: attestor.ChainInfo.attested_up_to_provisional:type_name -> attestor.AttestedRoot
	4,  // 3: attestor.InfoResponse.chains:type_name -> attestor.ChainInfo
	1,  // 4: attestor.AttestedUpToResponse.root:type_name -> attestor.AttestedRoot
	1,  // 5: attestor.AttestedRootAtOrBelowResponse.root:type_name -> attestor.AttestedRoot
	1,  // 6: attestor.WatchAttestedResponse.root:type_name -> attestor.AttestedRoot
	0,  // 7: attestor.VerifyStateRootRequest.run_mode:type_name -> attestor.RunMode
	3,  // 8: attestor.AttestorService.Info:input_type -> attestor.InfoRequest
	6,  // 9: attestor.AttestorService.AttestedUpTo:input_type -> attestor.AttestedUpToRequest
	8,  // 10: attestor.AttestorService.AttestedRootAtOrBelow:input_type -> attestor.AttestedRootAtOrBelowRequest
	10, // 11: attestor.AttestorService.WatchAttested:input_type -> attestor.WatchAttestedRequest
	12, // 12: attestor.AttestorService.VerifyStateRoot:input_type -> attestor.VerifyStateRootRequest
	5,  // 13: attestor.AttestorService.Info:output_type -> attestor.InfoResponse
	7,  // 14: attestor.AttestorService.AttestedUpTo:output_type -> attestor.AttestedUpToResponse
	9,  // 15: attestor.AttestorService.AttestedRootAtOrBelow:output_type -> attestor.AttestedRootAtOrBelowResponse
	11, // 16: attestor.AttestorService.WatchAttested:output_type -> attestor.WatchAttestedResponse
	13, // 17: attestor.AttestorService.VerifyStateRoot:output_type -> attestor.VerifyStateRootResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_attestor_attestor_proto_init() }
func file_attestor_attestor_proto_init() {
	if File_attestor_attestor_proto != nil {
		return
	}
	file_attestor_attestor_proto_msgTypes[0].OneofWrappers = []any{
		(*AttestedRoot_GameIndex)(nil),
		(*AttestedRoot_AssertionHash)(nil),
		(*AttestedRoot_LegacyNode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestor_attestor_proto_rawDesc), len(file_attestor_attestor_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attestor_attestor_proto_goTypes,
		DependencyIndexes: file_attestor_attestor_proto_depIdxs,
		EnumInfos:         file_attestor_attestor_proto_enumTypes,
		MessageInfos:      file_attestor_attestor_proto_msgTypes,
	}.Build()
	File_attestor_attestor_proto = out.File
	file_attestor_attestor_proto_goTypes = nil
	file_attestor_attestor_proto_depIdxs = nil
}
