// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: attestor/attestor.proto

package attestorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One attested output root from the feed.
type AttestedRoot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The L2 block number the root commits to.
	L2BlockNumber uint64 `protobuf:"varint,1,opt,name=l2_block_number,json=l2BlockNumber,proto3" json:"l2_block_number,omitempty"`
	// The 32-byte output root.
	Root []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	// Where the root came from: "derived" (self-computed at the configured
	// head) or "game" (a DisputeGameFactory proposal confirmed by replay).
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// The dispute game index; meaningful only when source is "game".
	GameIndex uint64 `protobuf:"varint,4,opt,name=game_index,json=gameIndex,proto3" json:"game_index,omitempty"`
	// True while the root awaits the finalized-head recheck.
	Provisional bool `protobuf:"varint,5,opt,name=provisional,proto3" json:"provisional,omitempty"`
	// Unix seconds when the attestor recorded the root.
	AttestedAt    int64 `protobuf:"varint,6,opt,name=attested_at,json=attestedAt,proto3" json:"attested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedRoot) Reset() {
	*x = AttestedRoot{}
	mi := &file_attestor_attestor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRoot) ProtoMessage() {}

func (x *AttestedRoot) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRoot.ProtoReflect.Descriptor instead.
func (*AttestedRoot) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{0}
}

func (x *AttestedRoot) GetL2BlockNumber() uint64 {
	if x != nil {
		return x.L2BlockNumber
	}
	return 0
}

func (x *AttestedRoot) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *AttestedRoot) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AttestedRoot) GetGameIndex() uint64 {
	if x != nil {
		return x.GameIndex
	}
	return 0
}

func (x *AttestedRoot) GetProvisional() bool {
	if x != nil {
		return x.Provisional
	}
	return false
}

func (x *AttestedRoot) GetAttestedAt() int64 {
	if x != nil {
		return x.AttestedAt
	}
	return 0
}

// The info request message.
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{1}
}

// Per-chain attestor status.
type ChainInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier (the op_source module's src_chain).
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// The configured gating head: "finalized", "safe" or "unsafe".
	AttestationHead string `protobuf:"bytes,2,opt,name=attestation_head,json=attestationHead,proto3" json:"attestation_head,omitempty"`
	// True once the replica has reported a sync status.
	ReplicaSeen bool `protobuf:"varint,3,opt,name=replica_seen,json=replicaSeen,proto3" json:"replica_seen,omitempty"`
	// The replica's unsafe L2 head (sequencer gossip).
	ReplicaUnsafeL2 uint64 `protobuf:"varint,4,opt,name=replica_unsafe_l2,json=replicaUnsafeL2,proto3" json:"replica_unsafe_l2,omitempty"`
	// The replica's safe L2 head (derived from L1).
	ReplicaSafeL2 uint64 `protobuf:"varint,5,opt,name=replica_safe_l2,json=replicaSafeL2,proto3" json:"replica_safe_l2,omitempty"`
	// The replica's finalized L2 head (derived from finalized L1).
	ReplicaFinalizedL2 uint64 `protobuf:"varint,6,opt,name=replica_finalized_l2,json=replicaFinalizedL2,proto3" json:"replica_finalized_l2,omitempty"`
	// Ingested respected-type games awaiting a verdict.
	PendingGames uint64 `protobuf:"varint,7,opt,name=pending_games,json=pendingGames,proto3" json:"pending_games,omitempty"`
	// The confirmed attested frontier; absent when nothing is attested yet.
	AttestedUpTo *AttestedRoot `protobuf:"bytes,8,opt,name=attested_up_to,json=attestedUpTo,proto3" json:"attested_up_to,omitempty"`
	// The frontier including provisional entries; absent when empty.
	AttestedUpToProvisional *AttestedRoot `protobuf:"bytes,9,opt,name=attested_up_to_provisional,json=attestedUpToProvisional,proto3" json:"attested_up_to_provisional,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ChainInfo) Reset() {
	*x = ChainInfo{}
	mi := &file_attestor_attestor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainInfo) ProtoMessage() {}

func (x *ChainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainInfo.ProtoReflect.Descriptor instead.
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{2}
}

func (x *ChainInfo) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *ChainInfo) GetAttestationHead() string {
	if x != nil {
		return x.AttestationHead
	}
	return ""
}

func (x *ChainInfo) GetReplicaSeen() bool {
	if x != nil {
		return x.ReplicaSeen
	}
	return false
}

func (x *ChainInfo) GetReplicaUnsafeL2() uint64 {
	if x != nil {
		return x.ReplicaUnsafeL2
	}
	return 0
}

func (x *ChainInfo) GetReplicaSafeL2() uint64 {
	if x != nil {
		return x.ReplicaSafeL2
	}
	return 0
}

func (x *ChainInfo) GetReplicaFinalizedL2() uint64 {
	if x != nil {
		return x.ReplicaFinalizedL2
	}
	return 0
}

func (x *ChainInfo) GetPendingGames() uint64 {
	if x != nil {
		return x.PendingGames
	}
	return 0
}

func (x *ChainInfo) GetAttestedUpTo() *AttestedRoot {
	if x != nil {
		return x.AttestedUpTo
	}
	return nil
}

func (x *ChainInfo) GetAttestedUpToProvisional() *AttestedRoot {
	if x != nil {
		return x.AttestedUpToProvisional
	}
	return nil
}

// The info response message.
type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status for every configured chain.
	Chains        []*ChainInfo `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{3}
}

func (x *InfoResponse) GetChains() []*ChainInfo {
	if x != nil {
		return x.Chains
	}
	return nil
}

// The attested-frontier request message.
type AttestedUpToRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// Whether provisional (below-finalized) roots count toward the frontier.
	IncludeProvisional bool `protobuf:"varint,2,opt,name=include_provisional,json=includeProvisional,proto3" json:"include_provisional,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttestedUpToRequest) Reset() {
	*x = AttestedUpToRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedUpToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedUpToRequest) ProtoMessage() {}

func (x *AttestedUpToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedUpToRequest.ProtoReflect.Descriptor instead.
func (*AttestedUpToRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{4}
}

func (x *AttestedUpToRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *AttestedUpToRequest) GetIncludeProvisional() bool {
	if x != nil {
		return x.IncludeProvisional
	}
	return false
}

// The attested-frontier response message.
type AttestedUpToResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when nothing qualifying has been attested yet.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// The frontier entry; set only when found.
	Root          *AttestedRoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedUpToResponse) Reset() {
	*x = AttestedUpToResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedUpToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedUpToResponse) ProtoMessage() {}

func (x *AttestedUpToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedUpToResponse.ProtoReflect.Descriptor instead.
func (*AttestedUpToResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{5}
}

func (x *AttestedUpToResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *AttestedUpToResponse) GetRoot() *AttestedRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

// The at-or-below query request message.
type AttestedRootAtOrBelowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// The inclusive upper bound on the L2 block number.
	L2BlockNumber uint64 `protobuf:"varint,2,opt,name=l2_block_number,json=l2BlockNumber,proto3" json:"l2_block_number,omitempty"`
	// Whether provisional (below-finalized) roots qualify.
	IncludeProvisional bool `protobuf:"varint,3,opt,name=include_provisional,json=includeProvisional,proto3" json:"include_provisional,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttestedRootAtOrBelowRequest) Reset() {
	*x = AttestedRootAtOrBelowRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRootAtOrBelowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRootAtOrBelowRequest) ProtoMessage() {}

func (x *AttestedRootAtOrBelowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRootAtOrBelowRequest.ProtoReflect.Descriptor instead.
func (*AttestedRootAtOrBelowRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{6}
}

func (x *AttestedRootAtOrBelowRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *AttestedRootAtOrBelowRequest) GetL2BlockNumber() uint64 {
	if x != nil {
		return x.L2BlockNumber
	}
	return 0
}

func (x *AttestedRootAtOrBelowRequest) GetIncludeProvisional() bool {
	if x != nil {
		return x.IncludeProvisional
	}
	return false
}

// The at-or-below query response message.
type AttestedRootAtOrBelowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when no qualifying root exists at or below the bound.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// The best qualifying entry; set only when found.
	Root          *AttestedRoot `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttestedRootAtOrBelowResponse) Reset() {
	*x = AttestedRootAtOrBelowResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestedRootAtOrBelowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestedRootAtOrBelowResponse) ProtoMessage() {}

func (x *AttestedRootAtOrBelowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestedRootAtOrBelowResponse.ProtoReflect.Descriptor instead.
func (*AttestedRootAtOrBelowResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{7}
}

func (x *AttestedRootAtOrBelowResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *AttestedRootAtOrBelowResponse) GetRoot() *AttestedRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

// The watch response message: one attested-frontier advance.
type WatchAttestedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new frontier entry.
	Root          *AttestedRoot `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchAttestedResponse) Reset() {
	*x = WatchAttestedResponse{}
	mi := &file_attestor_attestor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAttestedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAttestedResponse) ProtoMessage() {}

func (x *WatchAttestedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAttestedResponse.ProtoReflect.Descriptor instead.
func (*WatchAttestedResponse) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{8}
}

func (x *WatchAttestedResponse) GetRoot() *AttestedRoot {
	if x != nil {
		return x.Root
	}
	return nil
}

// The watch request message.
type WatchAttestedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source chain identifier.
	SrcChain string `protobuf:"bytes,1,opt,name=src_chain,json=srcChain,proto3" json:"src_chain,omitempty"`
	// Whether provisional (below-finalized) roots advance the streamed frontier.
	IncludeProvisional bool `protobuf:"varint,2,opt,name=include_provisional,json=includeProvisional,proto3" json:"include_provisional,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchAttestedRequest) Reset() {
	*x = WatchAttestedRequest{}
	mi := &file_attestor_attestor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchAttestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchAttestedRequest) ProtoMessage() {}

func (x *WatchAttestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attestor_attestor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchAttestedRequest.ProtoReflect.Descriptor instead.
func (*WatchAttestedRequest) Descriptor() ([]byte, []int) {
	return file_attestor_attestor_proto_rawDescGZIP(), []int{9}
}

func (x *WatchAttestedRequest) GetSrcChain() string {
	if x != nil {
		return x.SrcChain
	}
	return ""
}

func (x *WatchAttestedRequest) GetIncludeProvisional() bool {
	if x != nil {
		return x.IncludeProvisional
	}
	return false
}

var File_attestor_attestor_proto protoreflect.FileDescriptor

const file_attestor_attestor_proto_rawDesc = "" +
	"\n" +
	"\x17attestor/attestor.proto\x12\battestor\"\xc4\x01\n" +
	"\fAttestedRoot\x12&\n" +
	"\x0fl2_block_number\x18\x01 \x01(\x04R\rl2BlockNumber\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"game_index\x18\x04 \x01(\x04R\tgameIndex\x12 \n" +
	"\vprovisional\x18\x05 \x01(\bR\vprovisional\x12\x1f\n" +
	"\vattested_at\x18\x06 \x01(\x03R\n" +
	"attestedAt\"\r\n" +
	"\vInfoRequest\"\xb4\x03\n" +
	"\tChainInfo\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12)\n" +
	"\x10attestation_head\x18\x02 \x01(\tR\x0fattestationHead\x12!\n" +
	"\freplica_seen\x18\x03 \x01(\bR\vreplicaSeen\x12*\n" +
	"\x11replica_unsafe_l2\x18\x04 \x01(\x04R\x0freplicaUnsafeL2\x12&\n" +
	"\x0freplica_safe_l2\x18\x05 \x01(\x04R\rreplicaSafeL2\x120\n" +
	"\x14replica_finalized_l2\x18\x06 \x01(\x04R\x12replicaFinalizedL2\x12#\n" +
	"\rpending_games\x18\a \x01(\x04R\fpendingGames\x12<\n" +
	"\x0eattested_up_to\x18\b \x01(\v2\x16.attestor.AttestedRootR\fattestedUpTo\x12S\n" +
	"\x1aattested_up_to_provisional\x18\t \x01(\v2\x16.attestor.AttestedRootR\x17attestedUpToProvisional\";\n" +
	"\fInfoResponse\x12+\n" +
	"\x06chains\x18\x01 \x03(\v2\x13.attestor.ChainInfoR\x06chains\"c\n" +
	"\x13AttestedUpToRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12/\n" +
	"\x13include_provisional\x18\x02 \x01(\bR\x12includeProvisional\"X\n" +
	"\x14AttestedUpToResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\x04root\x18\x02 \x01(\v2\x16.attestor.AttestedRootR\x04root\"\x94\x01\n" +
	"\x1cAttestedRootAtOrBelowRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12&\n" +
	"\x0fl2_block_number\x18\x02 \x01(\x04R\rl2BlockNumber\x12/\n" +
	"\x13include_provisional\x18\x03 \x01(\bR\x12includeProvisional\"a\n" +
	"\x1dAttestedRootAtOrBelowResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12*\n" +
	"\x04root\x18\x02 \x01(\v2\x16.attestor.AttestedRootR\x04root\"C\n" +
	"\x15WatchAttestedResponse\x12*\n" +
	"\x04root\x18\x01 \x01(\v2\x16.attestor.AttestedRootR\x04root\"d\n" +
	"\x14WatchAttestedRequest\x12\x1b\n" +
	"\tsrc_chain\x18\x01 \x01(\tR\bsrcChain\x12/\n" +
	"\x13include_provisional\x18\x02 \x01(\bR\x12includeProvisional2\xd5\x02\n" +
	"\x0fAttestorService\x125\n" +
	"\x04Info\x12\x15.attestor.InfoRequest\x1a\x16.attestor.InfoResponse\x12M\n" +
	"\fAttestedUpTo\x12\x1d.attestor.AttestedUpToRequest\x1a\x1e.attestor.AttestedUpToResponse\x12h\n" +
	"\x15AttestedRootAtOrBelow\x12&.attestor.AttestedRootAtOrBelowRequest\x1a'.attestor.AttestedRootAtOrBelowResponse\x12R\n" +
	"\rWatchAttested\x12\x1e.attestor.WatchAttestedRequest\x1a\x1f.attestor.WatchAttestedResponse0\x01B$Z\"attestor/types/attestor;attestorpbb\x06proto3"

var (
	file_attestor_attestor_proto_rawDescOnce sync.Once
	file_attestor_attestor_proto_rawDescData []byte
)

func file_attestor_attestor_proto_rawDescGZIP() []byte {
	file_attestor_attestor_proto_rawDescOnce.Do(func() {
		file_attestor_attestor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attestor_attestor_proto_rawDesc), len(file_attestor_attestor_proto_rawDesc)))
	})
	return file_attestor_attestor_proto_rawDescData
}

var file_attestor_attestor_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_attestor_attestor_proto_goTypes = []any{
	(*AttestedRoot)(nil),                  // 0: attestor.AttestedRoot
	(*InfoRequest)(nil),                   // 1: attestor.InfoRequest
	(*ChainInfo)(nil),                     // 2: attestor.ChainInfo
	(*InfoResponse)(nil),                  // 3: attestor.InfoResponse
	(*AttestedUpToRequest)(nil),           // 4: attestor.AttestedUpToRequest
	(*AttestedUpToResponse)(nil),          // 5: attestor.AttestedUpToResponse
	(*AttestedRootAtOrBelowRequest)(nil),  // 6: attestor.AttestedRootAtOrBelowRequest
	(*AttestedRootAtOrBelowResponse)(nil), // 7: attestor.AttestedRootAtOrBelowResponse
	(*WatchAttestedResponse)(nil),         // 8: attestor.WatchAttestedResponse
	(*WatchAttestedRequest)(nil),          // 9: attestor.WatchAttestedRequest
}
var file_attestor_attestor_proto_depIdxs = []int32{
	0,  // 0: attestor.ChainInfo.attested_up_to:type_name -> attestor.AttestedRoot
	0,  // 1: attestor.ChainInfo.attested_up_to_provisional:type_name -> attestor.AttestedRoot
	2,  // 2: attestor.InfoResponse.chains:type_name -> attestor.ChainInfo
	0,  // 3: attestor.AttestedUpToResponse.root:type_name -> attestor.AttestedRoot
	0,  // 4: attestor.AttestedRootAtOrBelowResponse.root:type_name -> attestor.AttestedRoot
	0,  // 5: attestor.WatchAttestedResponse.root:type_name -> attestor.AttestedRoot
	1,  // 6: attestor.AttestorService.Info:input_type -> attestor.InfoRequest
	4,  // 7: attestor.AttestorService.AttestedUpTo:input_type -> attestor.AttestedUpToRequest
	6,  // 8: attestor.AttestorService.AttestedRootAtOrBelow:input_type -> attestor.AttestedRootAtOrBelowRequest
	9,  // 9: attestor.AttestorService.WatchAttested:input_type -> attestor.WatchAttestedRequest
	3,  // 10: attestor.AttestorService.Info:output_type -> attestor.InfoResponse
	5,  // 11: attestor.AttestorService.AttestedUpTo:output_type -> attestor.AttestedUpToResponse
	7,  // 12: attestor.AttestorService.AttestedRootAtOrBelow:output_type -> attestor.AttestedRootAtOrBelowResponse
	8,  // 13: attestor.AttestorService.WatchAttested:output_type -> attestor.WatchAttestedResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_attestor_attestor_proto_init() }
func file_attestor_attestor_proto_init() {
	if File_attestor_attestor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attestor_attestor_proto_rawDesc), len(file_attestor_attestor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attestor_attestor_proto_goTypes,
		DependencyIndexes: file_attestor_attestor_proto_depIdxs,
		MessageInfos:      file_attestor_attestor_proto_msgTypes,
	}.Build()
	File_attestor_attestor_proto = out.File
	file_attestor_attestor_proto_goTypes = nil
	file_attestor_attestor_proto_depIdxs = nil
}
