// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: attestor/attestor.proto

package attestorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttestorService_Info_FullMethodName                  = "/attestor.AttestorService/Info"
	AttestorService_AttestedUpTo_FullMethodName          = "/attestor.AttestorService/AttestedUpTo"
	AttestorService_AttestedRootAtOrBelow_FullMethodName = "/attestor.AttestorService/AttestedRootAtOrBelow"
	AttestorService_WatchAttested_FullMethodName         = "/attestor.AttestorService/WatchAttested"
	AttestorService_VerifyStateRoot_FullMethodName       = "/attestor.AttestorService/VerifyStateRoot"
)

// AttestorServiceClient is the client API for AttestorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AttestorService exposes independently verified L2 commitments.
type AttestorServiceClient interface {
	// Info reports every configured chain and its attestation frontier.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	// AttestedUpTo returns the highest independently verified L2 commitment for
	// a source chain.
	AttestedUpTo(ctx context.Context, in *AttestedUpToRequest, opts ...grpc.CallOption) (*AttestedUpToResponse, error)
	// AttestedRootAtOrBelow returns the highest independently verified L2
	// commitment at or below the requested block number.
	AttestedRootAtOrBelow(ctx context.Context, in *AttestedRootAtOrBelowRequest, opts ...grpc.CallOption) (*AttestedRootAtOrBelowResponse, error)
	// WatchAttested streams the current frontier, then a message whenever its
	// identity (height, root, provisional flag) changes. Without
	// include_provisional the frontier only grows; with it, a finality recheck
	// may also correct the streamed root in place, confirm it, or revoke it —
	// after a revocation the new, possibly lower, frontier is re-emitted.
	WatchAttested(ctx context.Context, in *WatchAttestedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchAttestedResponse], error)
	// VerifyStateRoot compares an expected root, and optionally a block hash,
	// with the replica's canonical block at the requested L2 height.
	VerifyStateRoot(ctx context.Context, in *VerifyStateRootRequest, opts ...grpc.CallOption) (*VerifyStateRootResponse, error)
}

type attestorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestorServiceClient(cc grpc.ClientConnInterface) AttestorServiceClient {
	return &attestorServiceClient{cc}
}

func (c *attestorServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, AttestorService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestorServiceClient) AttestedUpTo(ctx context.Context, in *AttestedUpToRequest, opts ...grpc.CallOption) (*AttestedUpToResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestedUpToResponse)
	err := c.cc.Invoke(ctx, AttestorService_AttestedUpTo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestorServiceClient) AttestedRootAtOrBelow(ctx context.Context, in *AttestedRootAtOrBelowRequest, opts ...grpc.CallOption) (*AttestedRootAtOrBelowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestedRootAtOrBelowResponse)
	err := c.cc.Invoke(ctx, AttestorService_AttestedRootAtOrBelow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestorServiceClient) WatchAttested(ctx context.Context, in *WatchAttestedRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchAttestedResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttestorService_ServiceDesc.Streams[0], AttestorService_WatchAttested_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchAttestedRequest, WatchAttestedResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttestorService_WatchAttestedClient = grpc.ServerStreamingClient[WatchAttestedResponse]

func (c *attestorServiceClient) VerifyStateRoot(ctx context.Context, in *VerifyStateRootRequest, opts ...grpc.CallOption) (*VerifyStateRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyStateRootResponse)
	err := c.cc.Invoke(ctx, AttestorService_VerifyStateRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestorServiceServer is the server API for AttestorService service.
// All implementations must embed UnimplementedAttestorServiceServer
// for forward compatibility.
//
// AttestorService exposes independently verified L2 commitments.
type AttestorServiceServer interface {
	// Info reports every configured chain and its attestation frontier.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	// AttestedUpTo returns the highest independently verified L2 commitment for
	// a source chain.
	AttestedUpTo(context.Context, *AttestedUpToRequest) (*AttestedUpToResponse, error)
	// AttestedRootAtOrBelow returns the highest independently verified L2
	// commitment at or below the requested block number.
	AttestedRootAtOrBelow(context.Context, *AttestedRootAtOrBelowRequest) (*AttestedRootAtOrBelowResponse, error)
	// WatchAttested streams the current frontier, then a message whenever its
	// identity (height, root, provisional flag) changes. Without
	// include_provisional the frontier only grows; with it, a finality recheck
	// may also correct the streamed root in place, confirm it, or revoke it —
	// after a revocation the new, possibly lower, frontier is re-emitted.
	WatchAttested(*WatchAttestedRequest, grpc.ServerStreamingServer[WatchAttestedResponse]) error
	// VerifyStateRoot compares an expected root, and optionally a block hash,
	// with the replica's canonical block at the requested L2 height.
	VerifyStateRoot(context.Context, *VerifyStateRootRequest) (*VerifyStateRootResponse, error)
	mustEmbedUnimplementedAttestorServiceServer()
}

// UnimplementedAttestorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestorServiceServer struct{}

func (UnimplementedAttestorServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAttestorServiceServer) AttestedUpTo(context.Context, *AttestedUpToRequest) (*AttestedUpToResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttestedUpTo not implemented")
}
func (UnimplementedAttestorServiceServer) AttestedRootAtOrBelow(context.Context, *AttestedRootAtOrBelowRequest) (*AttestedRootAtOrBelowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttestedRootAtOrBelow not implemented")
}
func (UnimplementedAttestorServiceServer) WatchAttested(*WatchAttestedRequest, grpc.ServerStreamingServer[WatchAttestedResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchAttested not implemented")
}
func (UnimplementedAttestorServiceServer) VerifyStateRoot(context.Context, *VerifyStateRootRequest) (*VerifyStateRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyStateRoot not implemented")
}
func (UnimplementedAttestorServiceServer) mustEmbedUnimplementedAttestorServiceServer() {}
func (UnimplementedAttestorServiceServer) testEmbeddedByValue()                         {}

// UnsafeAttestorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestorServiceServer will
// result in compilation errors.
type UnsafeAttestorServiceServer interface {
	mustEmbedUnimplementedAttestorServiceServer()
}

func RegisterAttestorServiceServer(s grpc.ServiceRegistrar, srv AttestorServiceServer) {
	// If the following call panics, it indicates UnimplementedAttestorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttestorService_ServiceDesc, srv)
}

func _AttestorService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestorService_AttestedUpTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestedUpToRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).AttestedUpTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_AttestedUpTo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).AttestedUpTo(ctx, req.(*AttestedUpToRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestorService_AttestedRootAtOrBelow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestedRootAtOrBelowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).AttestedRootAtOrBelow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_AttestedRootAtOrBelow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).AttestedRootAtOrBelow(ctx, req.(*AttestedRootAtOrBelowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestorService_WatchAttested_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchAttestedRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AttestorServiceServer).WatchAttested(m, &grpc.GenericServerStream[WatchAttestedRequest, WatchAttestedResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AttestorService_WatchAttestedServer = grpc.ServerStreamingServer[WatchAttestedResponse]

func _AttestorService_VerifyStateRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyStateRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestorServiceServer).VerifyStateRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestorService_VerifyStateRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestorServiceServer).VerifyStateRoot(ctx, req.(*VerifyStateRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttestorService_ServiceDesc is the grpc.ServiceDesc for AttestorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attestor.AttestorService",
	HandlerType: (*AttestorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _AttestorService_Info_Handler,
		},
		{
			MethodName: "AttestedUpTo",
			Handler:    _AttestorService_AttestedUpTo_Handler,
		},
		{
			MethodName: "AttestedRootAtOrBelow",
			Handler:    _AttestorService_AttestedRootAtOrBelow_Handler,
		},
		{
			MethodName: "VerifyStateRoot",
			Handler:    _AttestorService_VerifyStateRoot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchAttested",
			Handler:       _AttestorService_WatchAttested_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "attestor/attestor.proto",
}
