[package]
name = "cw-ics08-wasm-avalanche"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
avalanche-light-client = { workspace = true }
cosmwasm-std = { workspace = true, features = ["std", "stargate"] }
