name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: relayer/go.mod
          cache: true

      - name: Build
        working-directory: relayer
        run: go build ./...

      - name: Test
        working-directory: relayer
        run: go test ./...
